### ISSUE TITLE
Youtube videos for ToadML

### ISSUE THREAD

**Issue by iGherghe** [DasNaCl/toadml#1]
Hello,
on your website you mentioned that there are YT videos for the development of ToadML, however the links don't seem to work. Are you still planning to make the videos public or you changed your mind and plan to document ToadML on your blog only ?

Thanks

**Comment by DasNaCl** [comment]
Hi @iGherghe,

Thanks for raising the issue! Looks like I completely forgot to update the website. The link changed due to me moving from YT livestreams to twitch livestreams and re-organizing the YT channel structure.
There is a separate channel for the VODs now, the main channel will get a devlog (fun summary of a bunch of the past streams) hopefully in about a month.

Here is the link: https://www.youtube.com/playlist?list=PLGVwSO7qerMKCS1lNXt4KIdtJENoMbL46

Again, much appreciated feedback! :smile:

**Comment by DasNaCl** [comment]
heads up: updated the links on the website :+1:

**Comment by iGherghe** [comment]
Great! Watching the first video now.
