### ISSUE TITLE
IR related to ToadML ?

### ISSUE THREAD

**Issue by ccrashes** [DasNaCl/toadml#2]
Hello and thanks for your tutorials .

I'm following this video : 
https://www.youtube.com/watch?v=sZLa7rFn2BA 

Where you're designing an intermediate representation for your compiler . As I checked this repository as it linked to your video, I didn't see the IR part in this code repository? Is that mean this part is not OpenSourced or you have plan to make it available on the repo ?

Thanks.

**Comment by DasNaCl** [comment]
Hi,
due to life:tm: I took the freedom to switch gears with this project. There will be no streaming anymore.
Unfortunately, it looks like the OCaml version that the streams/videos are about is also gone; I don't really remember but it looks like I have them erased from this repo.
Eventually, I'll add a similar IR in this Rusty version.
Thanks for the interest and sorry for the inconveniences. I'll update the website and the yt channel soon.
